=== clpadron/ELM-JSONgenerated/New folder/edci_presentation-generated-schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "@targetNamespace": {"type": "string"},
        "@elementFormDefault": {"type": "string"},
        "@version": {"type": "string"},
        "include": {"$ref": "#/definitions/include_type"},
        "element": {"$ref": "#/definitions/element_type"},
        "complexType": {"$ref": "#/definitions/complexType_type"}
    },
    "definitions": {
        "include_type": {
            "type": "object",
            "properties": {
                "@schemaLocation": {"type": "string"}
            }
        },
        "annotation_type": {
            "type": "object",
            "properties": {
                "documentation": {"type": "string"}
            }
        },
        "element_type": {
            "type": "object",
            "properties": {
                "@name": {"type": "string"},
                "@type": {"type": "string"},
                "annotation": {"$ref": "#/definitions/annotation_type"}
            }
        },
        "element2_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@name": {"type": "string"},
                    "@type": {"type": "string"},
                    "@minOccurs": {"type": "string"},
                    "@maxOccurs": {"type": "string"}
                },
                "required": [
                    "@name",
                    "@type"
                ]
            }
        },
        "sequence_type": {
            "type": "object",
            "properties": {
                "element": {"$ref": "#/definitions/element2_type"}
            }
        },
        "enumeration_type": {
            "type": "object",
            "properties": {
                "@value": {"type": "string"}
            }
        },
        "restriction_type": {
            "type": "object",
            "properties": {
                "@base": {"type": "string"},
                "enumeration": {"$ref": "#/definitions/enumeration_type"}
            }
        },
        "simpleType_type": {
            "type": "object",
            "properties": {
                "restriction": {"$ref": "#/definitions/restriction_type"}
            }
        },
        "attribute_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@name": {"type": "string"},
                    "@type": {"type": "string"},
                    "@use": {"type": "string"},
                    "annotation": {"$ref": "#/definitions/annotation_type"},
                    "@default": {"type": "string"},
                    "simpleType": {"$ref": "#/definitions/simpleType_type"}
                },
                "required": [
                    "annotation",
                    "@name",
                    "@use"
                ]
            }
        },
        "attribute2_type": {
            "type": "object",
            "properties": {
                "@name": {"type": "string"},
                "@type": {"type": "string"},
                "@use": {"type": "string"},
                "annotation": {"$ref": "#/definitions/annotation_type"}
            }
        },
        "extension_type": {
            "type": "object",
            "properties": {
                "@base": {"type": "string"},
                "attribute": {"$ref": "#/definitions/attribute2_type"}
            }
        },
        "complexContent_type": {
            "type": "object",
            "properties": {
                "extension": {"$ref": "#/definitions/extension_type"}
            }
        },
        "complexType_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@name": {"type": "string"},
                    "annotation": {"$ref": "#/definitions/annotation_type"},
                    "sequence": {"$ref": "#/definitions/sequence_type"},
                    "attribute": {"$ref": "#/definitions/attribute_type"},
                    "complexContent": {"$ref": "#/definitions/complexContent_type"}
                },
                "required": ["@name"]
            }
        }
    }
}

=== clpadron/ELM-JSONgenerated/New folder/edci_credential.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.4.0",
   "include": {
      "@schemaLocation": "edci_credentialTypes.xsd"
   },
   "element": {
      "@name": "europassCredential",
      "@type": "EuropassCredentialType",
      "annotation": {
         "documentation": "A set of claims made by an issuer in Europe, using the Europass Standards.  A Europass credential is a set of one or more claims which may be used to demonstrate that the owner has certain skills or has achieved certain learning outcomes through formal, non-formal or informal learning."
      },
      "unique": [
         {
            "@name": "title",
            "selector": {
               "@xpath": "eup:title"
            },
            "field": {
               "@xpath": "@lang"
            }
         },
         {
            "@name": "description",
            "selector": {
               "@xpath": "eup:description/eup:text"
            },
            "field": {
               "@xpath": "@lang"
            }
         }
      ],
      "key": [
         {
            "@name": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:learningSpecificationReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "learningActivitySpecificationKey",
            "selector": {
               "@xpath": "eup:learningActivitySpecificationReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "assessmentSpecificationKey",
            "selector": {
               "@xpath": "eup:assessmentSpecificationReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "entitlementSpecificationKey",
            "selector": {
               "@xpath": "eup:entitlementSpecificationReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "learningOpportunityKey",
            "selector": {
               "@xpath": "eup:learningOpportunityReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "accreditationKey",
            "selector": {
               "@xpath": "eup:accreditationReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "frameworkKey",
            "selector": {
               "@xpath": "eup:semanticFrameworkReferences/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "agentKey",
            "selector": {
               "@xpath": "eup:agentReferences/eup:organization"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "scoringSchemeKey",
            "selector": {
               "@xpath": "eup:scoringSchemeReferences/eup:scoringScheme"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "achievementKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:achievements/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "activityKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:activities/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "assessmentKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:assessments/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "entitlementKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:entitlements/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         },
         {
            "@name": "awardingKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:awardings/eup:*"
            },
            "field": {
               "@xpath": "@id"
            }
         }
      ],
      "keyref": [
         {
            "@name": "learningSpecKeyRef1",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:learningSpecificationReferences/eup:*/eup:hasPart"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef2",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:learningSpecificationReferences/eup:*/eup:specializationOf"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef3",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:achievements/eup:learningAchievement/eup:specifiedBy"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef4",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:achievements/eup:qualificationAward/eup:specifiedBy"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef5",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:learningOpportunityReferences/eup:*/eup:specifiedBy"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef6",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:assessmentSpecificationReferences/eup:*/eup:proves"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef7",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:learningActivitySpecificationReferences/eup:*/eup:teaches"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef8",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:accreditationReferences/eup:*/eup:limitQualification"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningSpecKeyRef9",
            "@refer": "learningSpecificationKey",
            "selector": {
               "@xpath": "eup:entitlementSpecificationReferences/eup:*/eup:mayResultFrom"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningActSpecKeyRef1",
            "@refer": "learningActivitySpecificationKey",
            "selector": {
               "@xpath": "eup:learningActivitySpecificationReferences/eup:*/eup:hasPart"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningActSpecKeyRef2",
            "@refer": "learningActivitySpecificationKey",
            "selector": {
               "@xpath": "eup:learningActivitySpecificationReferences/eup:*/eup:specializationOf"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningActSpecKeyRef3",
            "@refer": "learningActivitySpecificationKey",
            "selector": {
               "@xpath": "eup:learningSpecificationReferences/eup:*/eup:learningActivitySpecification"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "learningActSpecKeyRef4",
            "@refer": "learningActivitySpecificationKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:activities/eup:activity/eup:specifiedBy"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "assessmentSpecKeyRef1",
            "@refer": "assessmentSpecificationKey",
            "selector": {
               "@xpath": "eup:assessmentSpecificationReferences/eup:*/eup:hasPart"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "assessmentSpecKeyRef2",
            "@refer": "assessmentSpecificationKey",
            "selector": {
               "@xpath": "eup:assessmentSpecificationReferences/eup:*/eup:specializationOf"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "assessmentSpecKeyRef3",
            "@refer": "assessmentSpecificationKey",
            "selector": {
               "@xpath": "eup:learningSpecificationReferences/eup:*/eup:assessmentSpecification"
            },
            "field": {
               "@xpath": "@idref"
            }
         },
         {
            "@name": "assessmentSpecKeyRef4",
            "@refer": "assessmentSpecificationKey",
            "selector": {
               "@xpath": "eup:credentialSubject/eup:assessments/eup:assessment/eup:specifiedBy"
            },
