=== clpadron/ELM-JSONgenerated/New folder/edci_contact-generated-schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "@targetNamespace": {"type": "string"},
        "@elementFormDefault": {"type": "string"},
        "@version": {"type": "string"},
        "include": {"$ref": "#/definitions/include_type"},
        "complexType": {"$ref": "#/definitions/complexType_type"}
    },
    "definitions": {
        "include_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@schemaLocation": {"type": "string"}
                },
                "required": ["@schemaLocation"]
            }
        },
        "annotation_type": {
            "type": "object",
            "properties": {
                "documentation": {"type": "null"}
            }
        },
        "annotation2_type": {
            "type": "object",
            "properties": {
                "documentation": {"type": "string"}
            }
        },
        "element_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@name": {"type": "string"},
                    "@type": {"type": "string"},
                    "@minOccurs": {"type": "string"},
                    "@maxOccurs": {"type": "string"},
                    "annotation": {"$ref": "#/definitions/annotation2_type"}
                },
                "required": [
                    "@minOccurs",
                    "annotation",
                    "@name",
                    "@maxOccurs",
                    "@type"
                ]
            }
        },
        "sequence_type": {
            "type": "object",
            "properties": {
                "element": {"$ref": "#/definitions/element_type"}
            }
        },
        "complexType_type": {
            "type": "object",
            "properties": {
                "@name": {"type": "string"},
                "annotation": {"$ref": "#/definitions/annotation_type"},
                "sequence": {"$ref": "#/definitions/sequence_type"}
            }
        }
    }
}

=== clpadron/ELM-JSONgenerated/New folder/edci_contact.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.4.0",
   "include": [
      {
         "@schemaLocation": "edci_simpleContentTypes.xsd"
      },
      {
         "@schemaLocation": "edci_commonTypes.xsd"
      }
   ],
   "complexType": {
      "@name": "ContactPointType",
      "annotation": {
         "documentation": null
      },
      "sequence": {
         "element": [
            {
               "@name": "note",
               "@type": "NoteType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "A note about the contactpoint. E.g. a note about the usage and availibility about this contactpoint."
               }
            },
            {
               "@name": "description",
               "@type": "NoteType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "A free text describing the contact details."
               }
            },
            {
               "@name": "address",
               "@type": "AddressType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "A postal address used for contacting the agent."
               }
            },
            {
               "@name": "phone",
               "@type": "PhoneType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "A phone number used for contacting the agent."
               }
            },
            {
               "@name": "mailBox",
               "@type": "MBoxType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "An email address used for contacting the agent."
               }
            },
            {
               "@name": "webresource",
               "@type": "InteractiveWebResourceType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "A contact form used for contacting the agent."
               }
            },
            {
               "@name": "wallet",
               "@type": "MBoxType",
               "@minOccurs": "0",
               "@maxOccurs": "unbounded",
               "annotation": {
                  "documentation": "The address of an electronic wallet where credentials may be deposited."
               }
            }
         ]
      }
   }
}
