=== clpadron/ELM-JSONgenerated/New folder/w3c_verifiableCredentials-generated-schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "@targetNamespace": {"type": "string"},
        "@elementFormDefault": {"type": "string"},
        "@attributeFormDefault": {"type": "string"},
        "annotation": {"$ref": "#/definitions/annotation_type"}
    },
    "definitions": {
        "annotation_type": {
            "type": "object",
            "properties": {
                "documentation": {"type": "string"}
            }
        }
    }
}

=== clpadron/ELM-JSONgenerated/New folder/w3c_verifiableCredentials.json
{
    "@targetNamespace": "http://data.europa.eu/europass/model/credentials/w3c#",
    "@elementFormDefault": "qualified",
    "@attributeFormDefault": "unqualified",
    "annotation": {"documentation": "The W3C Verifiable Credential Recommendation does not provide an XML Schema for describing Verifiable Credentials."}
}
