=== clpadron/ELM-JSONgenerated/New folder/imported/edci_esco_iscedf2013-generated-schema.json
{
    "$schema": "https://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "@targetNamespace": {"type": "string"},
        "@elementFormDefault": {"type": "string"},
        "@version": {"type": "string"},
        "simpleType": {"$ref": "#/definitions/simpleType_type"}
    },
    "definitions": {
        "annotation_type": {
            "type": "object",
            "properties": {
                "documentation": {"type": "null"}
            }
        },
        "enumeration_type": {
            "type": "array",
            "minItems": 0,
            "items": {
                "type": "object",
                "properties": {
                    "@value": {"type": "string"}
                },
                "required": ["@value"]
            }
        },
        "restriction_type": {
            "type": "object",
            "properties": {
                "@base": {"type": "string"},
                "enumeration": {"$ref": "#/definitions/enumeration_type"}
            }
        },
        "simpleType_type": {
            "type": "object",
            "properties": {
                "@name": {"type": "string"},
                "annotation": {"$ref": "#/definitions/annotation_type"},
                "restriction": {"$ref": "#/definitions/restriction_type"}
            }
        }
    }
}

=== clpadron/ELM-JSONgenerated/New folder/imported/edci_mdr_currency.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.2.0",
   "simpleType": {
      "@name": "MDRCurrencyEnumType",
      "annotation": {
         "documentation": null
      },
      "restriction": {
         "@base": "xs:anyURI",
         "enumeration": [
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/EUR"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/GBP"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/ISK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/NOK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/SEK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/SKK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/CZK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/DKK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/CHF"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/currency/TRY"
            }
         ]
      }
   }
}

=== clpadron/ELM-JSONgenerated/New folder/imported/edci_esco_eqf.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.2.0",
   "simpleType": {
      "@name": "EQFLevelEnumType",
      "annotation": {
         "documentation": null
      },
      "restriction": {
         "@base": "xs:anyURI",
         "enumeration": [
            {
               "@value": "http://data.europa.eu/esco/eqf/1"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/2"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/3"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/4"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/5"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/6"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/7"
            },
            {
               "@value": "http://data.europa.eu/esco/eqf/8"
            }
         ]
      }
   }
}

=== clpadron/ELM-JSONgenerated/New folder/imported/edci_mdr_languages.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.2.0",
   "simpleType": {
      "@name": "MDRLanguageCodeEnumType",
      "annotation": {
         "documentation": null
      },
      "restriction": {
         "@base": "xs:anyURI",
         "enumeration": [
            {
               "@value": "http://publications.europa.eu/resource/authority/language/BUL"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/CES"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/DAN"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/DEU"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/ELL"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/ENG"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/SPA"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/EST"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/FIN"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/FRA"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/GLE"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/HRV"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/HUN"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/ISL"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/ITA"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/LIT"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/LAV"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/MLT"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/NLD"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/NOR"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/POL"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/POR"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/RON"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/SLK"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/SLV"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/language/SWE"
            }
         ]
      }
   }
}

=== clpadron/ELM-JSONgenerated/New folder/imported/edci_mdr_humansex.json
{
   "@targetNamespace": "http://data.europa.eu/europass/model/credentials#",
   "@elementFormDefault": "qualified",
   "@version": "0.2.0",
   "simpleType": {
      "@name": "MDRHumanSexEnumType",
      "annotation": {
         "documentation": null
      },
      "restriction": {
         "@base": "xs:anyURI",
         "enumeration": [
            {
               "@value": "http://publications.europa.eu/resource/authority/human-sex/MALE"
            },
            {
               "@value": "http://publications.europa.eu/resource/authority/human-sex/FEMALE"
            }
         ]
      }
   }
}
